name: adamstracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  sliding_up_panel: ^2.0.0+1
  wakelock: ^0.5.2
  scoped_model: ^2.0.0-nullsafety.0
  flutter_easyloading: ^3.0.0
  google_sign_in: ^5.0.4
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_charts: ^19.2.48
  numberpicker: ^2.1.1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  mysql1: ^0.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "C:/Users/aelme/Desktop/adamstracker/assets/logo/drawable-mdpi/SPRK_default_preset_name_custom â€“ 1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
